import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
  AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube
} from 'react-icons/ai'
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbyted</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Dimitri Macro</h2>
            <h3 className='text-2xl py-2'>Developer and designer</h3>
            <p className='text-medium py-5 leading-8 text-gray-800'>Freelancer providing serviecs for programming and needs.Join me down below and lets get craking</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-80'>
              Since the beginnig of my journey as a freel developer, Ive done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500"> startup </span>and collaborated with talented people to create digit products for both business 
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of servies, including programming and teaching
            </p>
          </div>

          <div>
            <div className='text-center shadow-lg p-10
             rounded-xl my-10'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beutiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10
             rounded-xl my-10'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beutiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            
            <div className='text-center shadow-lg p-10
             rounded-xl my-10 relative mx-auto'>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beutiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
